version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
      - ./database:/docker-entrypoint-initdb.d:z
    networks:
      - dev_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/master
      KC_DB_USERNAME: dev_user
      KC_DB_PASSWORD: dev_pass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.import=/opt/keycloak/data/import/"
    volumes:
      - ./keycloak_data:/opt/keycloak/data:z
    ports:
      - 8087:8080
      - 8443:8443
    depends_on:
      - postgres
    networks:
      - dev_net
    command: >
      start-dev 
      --import-realm 
      --features=scripts 
      -Dkeycloak.profile.feature.upload_scripts=enabled

  keycloak_init:
    image: node:20-alpine
    depends_on:
      - keycloak
    entrypoint: [ "sh", "-c" ]
    command: |
      "
      apk add --no-cache curl jq >/dev/null;
      echo '⏳ Aguardando Keycloak ficar disponível...';
      until curl -s http://keycloak:8080/realms/master; do
        sleep 2;
      done;
      echo '✅ Keycloak está pronto, executando script...';
      sh /scripts/post-start.sh;
      "
    volumes:
      - ./scripts:/scripts:ro
    networks:
      - dev_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quarkus_backend
    restart: always
    environment:
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_pass
      DB_URL: jdbc:postgresql://postgres:5432/master
      KC_URL: http://keycloak:8080
      TODO_CLIENT_SECRET: jJIhoDhAXYwzXmnsFk7xYIieuw9LqAdS
      ADMIN_CLIENT_SECRET: td0sJSxg6xVjUuK1JnAjic63iJ4zVf8e
    depends_on:
      - postgres
      - keycloak
      - keycloak_init
    ports:
      - "8087:8080"
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16