CREATE TABLE EVENTS.EVENT_DOMAIN ( -- Tabela de domínio de eventos
    ID_EVENT_DOMAIN BIGSERIAL PRIMARY KEY, -- Identificador único de domínio de evento
    NM_EVENT_DOMAIN VARCHAR(50) NOT NULL -- Nome do domínio do evento
);

COMMENT ON TABLE EVENTS.EVENT_DOMAIN IS 'Tabela de domínio de eventos';
COMMENT ON COLUMN EVENTS.EVENT_DOMAIN.ID_EVENT_DOMAIN IS 'Identificador único de domínio de evento';
COMMENT ON COLUMN EVENTS.EVENT_DOMAIN.NM_EVENT_DOMAIN IS 'Nome do domínio do evento';

INSERT INTO EVENTS.EVENT_DOMAIN (ID_EVENT_DOMAIN, NM_EVENT_DOMAIN)
    VALUES (100, 'Usuário');
INSERT INTO EVENTS.EVENT_DOMAIN (ID_EVENT_DOMAIN, NM_EVENT_DOMAIN)
    VALUES (200, 'Atividade');