CREATE TABLE EVENTS.EVENT ( -- Tabela de eventos
    ID_EVENT BIGSERIAL PRIMARY KEY, -- Identificador único de evento
    ID_EVENT_FAIXA BIGINT NOT NULL, -- Faixa do evento
    ID_EVENT_DOMAIN BIGINT NOT NULL, -- Domínio do evento
    NM_EVENT VARCHAR(50) NOT NULL -- Nome do evento
);

COMMENT ON TABLE EVENTS.EVENT IS 'Tabela de eventos';
COMMENT ON COLUMN EVENTS.EVENT.ID_EVENT IS 'Identificador único de evento';
COMMENT ON COLUMN EVENTS.EVENT.ID_EVENT_FAIXA IS 'Faixa do evento';
COMMENT ON COLUMN EVENTS.EVENT.ID_EVENT_DOMAIN IS 'Domínio do evento';
COMMENT ON COLUMN EVENTS.EVENT.NM_EVENT IS 'Nome do evento';

ALTER TABLE EVENTS.EVENT
    ADD CONSTRAINT FK_EVENT_EVENT_DOMAIN_ID_EVENT_DOMAIN
        FOREIGN KEY (ID_EVENT_DOMAIN) REFERENCES EVENTS.EVENT_DOMAIN(ID_EVENT_DOMAIN);

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (1, 100, 'Usuário criado');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (2, 100, 'Usuário desativado');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (1, 200, 'Atividade criada');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (2, 200, 'Atividade desativada');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (3, 200, 'Atividade realizada');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (4, 200, 'Atividade tornada pública');

INSERT INTO EVENTS.EVENT (ID_EVENT_FAIXA, ID_EVENT_DOMAIN, NM_EVENT)
    VALUES (5, 200, 'Atividade tornada privada');

