CREATE TABLE TODO.USER_EVENT ( -- Tabela de eventos do usuário
    ID_USER_EVENT BIGSERIAL PRIMARY KEY, -- Identificador único de evento
    ID_EVENT BIGINT NOT NULL, -- Evento ocorrido
    ID_USER BIGINT NOT NULL, -- Usuário do evento
    ID_USER_OPERATOR BIGINT NOT NULL, -- Usuário que realizou o evento
    DT_OCCURRENCE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- Data de acontecimento do evento
);

COMMENT ON TABLE TODO.USER_EVENT IS 'Tabela de eventos do usuário';
COMMENT ON COLUMN TODO.USER_EVENT.ID_USER_EVENT IS 'Identificador único de evento';
COMMENT ON COLUMN TODO.USER_EVENT.ID_EVENT IS 'Evento ocorrido';
COMMENT ON COLUMN TODO.USER_EVENT.ID_USER IS 'Usuário do evento';
COMMENT ON COLUMN TODO.USER_EVENT.ID_USER_OPERATOR IS 'Usuário que realizou o evento';
COMMENT ON COLUMN TODO.USER_EVENT.DT_OCCURRENCE IS 'Data de acontecimento do evento';

ALTER TABLE TODO.USER_EVENT
    ADD CONSTRAINT FK_USER_EVENT_EVENT_ID_EVENT
        FOREIGN KEY (ID_EVENT) REFERENCES EVENTS.EVENT(ID_EVENT),
    ADD CONSTRAINT FK_USER_EVENT_USER_ID_USER
        FOREIGN KEY (ID_USER) REFERENCES TODO.USER(ID_USER),
    ADD CONSTRAINT FK_USER_EVENT_USER_ID_USER_OPERATOR
        FOREIGN KEY (ID_USER_OPERATOR) REFERENCES TODO.USER(ID_USER);
