CREATE TABLE TODO.TASK_EVENT ( -- Tabela de eventos da atividade
    ID_TASK_EVENT BIGSERIAL PRIMARY KEY, -- Identificador único de evento
    ID_EVENT BIGINT NOT NULL, -- Evento ocorrido
    ID_TASK BIGINT NOT NULL, -- Atividade do evento
    ID_USER_OPERATOR BIGINT NOT NULL, -- Usuário que realizou o evento
    DT_OCCURRENCE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- Data de acontecimento do evento
);

COMMENT ON TABLE TODO.TASK_EVENT IS 'Tabela de eventos da atividade';
COMMENT ON COLUMN TODO.TASK_EVENT.ID_TASK_EVENT IS 'Identificador único de evento';
COMMENT ON COLUMN TODO.TASK_EVENT.ID_EVENT IS 'Evento ocorrido';
COMMENT ON COLUMN TODO.TASK_EVENT.ID_TASK IS 'Atividade do evento';
COMMENT ON COLUMN TODO.TASK_EVENT.ID_USER_OPERATOR IS 'Usuário que realizou o evento';
COMMENT ON COLUMN TODO.TASK_EVENT.DT_OCCURRENCE IS 'Data de acontecimento do evento';

ALTER TABLE TODO.TASK_EVENT
    ADD CONSTRAINT FK_TASK_EVENT_EVENT_ID_EVENT
        FOREIGN KEY (ID_EVENT) REFERENCES EVENTS.EVENT(ID_EVENT),
    ADD CONSTRAINT FK_TASK_EVENT_TASK_ID_TASK
        FOREIGN KEY (ID_TASK) REFERENCES TODO.TASK(ID_TASK),
    ADD CONSTRAINT FK_TASK_EVENT_USER_ID_USER_OPERATOR
        FOREIGN KEY (ID_USER_OPERATOR) REFERENCES TODO.USER(ID_USER);
